# Generated by Django 5.2.3 on 2025-06-24 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Tecnico', 'Tecnico')], default='Cliente', max_length=10)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residenza', models.CharField(blank=True, max_length=200, null=True)),
                ('specializzazione', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoAcquistabile',
            fields=[
                ('id_prodotto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('immagine', models.ImageField(upload_to='prodotti/')),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Il prezzo non può essere negativo')])),
                ('quantita_rimasta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='La quantità non può essere negativa')])),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='ElettronicaIovine.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id_ordine', models.AutoField(primary_key=True, serialize=False)),
                ('stato', models.CharField(choices=[('Accolto', 'Accolto'), ('In lavorazione', 'In lavorazione'), ('Da ritirare', 'Da ritirare')], default='Accolto', max_length=20)),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('prezzo_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='ElettronicaIovine.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assistenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('Accolto', 'Accolto'), ('In lavorazione', 'In lavorazione'), ('Da ritirare', 'Da ritirare')], default='Accolto', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('intestazione', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistenze_richieste', to='ElettronicaIovine.user')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistenze_fornite', to='ElettronicaIovine.user')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_quantita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='ElettronicaIovine.ordine')),
                ('id_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElettronicaIovine.prodottoacquistabile')),
            ],
            options={
                'unique_together': {('id_prodotto', 'id_ordine')},
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Il voto deve essere almeno 1'), django.core.validators.MaxValueValidator(5, message='Il voto non può essere superiore a 5')])),
                ('descrizione', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_date', to='ElettronicaIovine.user')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_ricevute', to='ElettronicaIovine.user')),
            ],
            options={
                'unique_together': {('id_cliente', 'id_tecnico')},
            },
        ),
    ]
