# Generated by Django 5.2.3 on 2025-06-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElettronicaIovine', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id_utente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Tecnico', 'Tecnico')], default='Cliente', max_length=10)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residenza', models.CharField(blank=True, max_length=200, null=True)),
                ('specializzazione', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='assistenza',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='assistenza',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistenze_fornite', to='ElettronicaIovine.utente'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='ElettronicaIovine.utente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistenza',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistenze_richieste', to='ElettronicaIovine.utente'),
        ),
        migrations.AlterField(
            model_name='prodottoacquistabile',
            name='id_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='ElettronicaIovine.utente'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_date', to='ElettronicaIovine.utente'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='id_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_ricevute', to='ElettronicaIovine.utente'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
