# Generated by Django 5.2.3 on 2025-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElettronicaIovine', '0003_utente_remove_ordine_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottoacquistabile',
            name='immagine',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
